import { DriveAccount, DriveFile, SyncRule, DriveNotification } from '../types/drive';

export const INITIAL_DEMO_ACCOUNTS: DriveAccount[] = [
  {
    id: 'acc-work',
    email: 'alex.corporate@company.com',
    name: 'Alex Pratama (Work Workspace)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    isPrimary: false,
    accessToken: 'demo_token_work',
    tokenExpiresAt: Date.now() + 86400000,
    quota: {
      total: 30 * 1024 * 1024 * 1024, // 30 GB
      used: 19.4 * 1024 * 1024 * 1024,
      usedInDrive: 18.2 * 1024 * 1024 * 1024,
      usedInTrash: 1.2 * 1024 * 1024 * 1024,
    },
    status: 'connected',
    lastSyncTime: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    color: '#3B82F6', // Blue
  },
  {
    id: 'acc-personal',
    email: 'alex.pratama.dev@gmail.com',
    name: 'Alex Pratama (Personal Vault)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    isPrimary: false,
    accessToken: 'demo_token_personal',
    tokenExpiresAt: Date.now() + 86400000,
    quota: {
      total: 15 * 1024 * 1024 * 1024, // 15 GB
      used: 8.7 * 1024 * 1024 * 1024,
      usedInDrive: 7.9 * 1024 * 1024 * 1024,
      usedInTrash: 0.8 * 1024 * 1024 * 1024,
    },
    status: 'connected',
    lastSyncTime: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    color: '#10B981', // Emerald
  },
  {
    id: 'acc-research',
    email: 'research.lab@university.ac.id',
    name: 'Lab Riset Multimedia (Academic)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    isPrimary: false,
    accessToken: 'demo_token_research',
    tokenExpiresAt: Date.now() + 86400000,
    quota: {
      total: 100 * 1024 * 1024 * 1024, // 100 GB
      used: 64.1 * 1024 * 1024 * 1024,
      usedInDrive: 62.8 * 1024 * 1024 * 1024,
      usedInTrash: 1.3 * 1024 * 1024 * 1024,
    },
    status: 'connected',
    lastSyncTime: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    color: '#8B5CF6', // Purple
  },
];

export const INITIAL_DEMO_FILES: DriveFile[] = [
  {
    id: 'f-1',
    accountId: 'acc-work',
    accountEmail: 'alex.corporate@company.com',
    accountName: 'Alex Pratama (Work Workspace)',
    name: 'Laporan_Keuangan_Kuartal_3_2026.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'spreadsheet',
    size: 4820000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    isEncrypted: false,
    shared: true,
    shareSettings: {
      linkId: 'sh-link-101',
      shareUrl: 'https://xxcloud.internal/share/sh-link-101',
      accessRole: 'viewer',
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
      isPasswordProtected: true,
      allowDownload: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      accessCount: 14,
      status: 'active',
    },
    starred: true,
    path: '/Finance/2026',
    tags: ['Keuangan', 'Q3', 'Laporan'],
  },
  {
    id: 'f-2',
    accountId: 'acc-work',
    accountEmail: 'alex.corporate@company.com',
    accountName: 'Alex Pratama (Work Workspace)',
    name: 'Roadmap_Strategis_Teknologi_2026-2027.pdf',
    mimeType: 'application/pdf',
    category: 'pdf',
    size: 14200000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isEncrypted: false,
    shared: false,
    starred: true,
    path: '/Strategy',
    tags: ['Tech', 'Roadmap', 'Confidential'],
  },
  {
    id: 'f-3',
    accountId: 'acc-personal',
    accountEmail: 'alex.pratama.dev@gmail.com',
    accountName: 'Alex Pratama (Personal Vault)',
    name: 'Kunci_Privat_Wallet_Keluarga.omnienc',
    mimeType: 'application/octet-stream',
    category: 'encrypted',
    size: 89000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    isEncrypted: true,
    encryptionMeta: {
      algorithm: 'AES-256-GCM',
      iv: 'SGFzaE1vY2tJVjEyQnl0ZXMA',
      salt: 'U2FsdEV4YW1wbGVTYWx0MTY=',
      originalMimeType: 'text/plain',
      originalName: 'Kunci_Privat_Wallet_Keluarga.txt',
      originalSize: 720,
      checksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      encryptedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    },
    encryptedContentPreview: '7a9c8f041b3e5d82991048f029c910fae1208573...',
    shared: false,
    starred: true,
    path: '/E2E_Secure_Vault',
    tags: ['E2EE', 'Kripto', 'Sangat Rahasia'],
  },
  {
    id: 'f-4',
    accountId: 'acc-personal',
    accountEmail: 'alex.pratama.dev@gmail.com',
    accountName: 'Alex Pratama (Personal Vault)',
    name: 'Database_Kredensial_Sandi_2026.omnienc',
    mimeType: 'application/octet-stream',
    category: 'encrypted',
    size: 340000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    isEncrypted: true,
    encryptionMeta: {
      algorithm: 'AES-256-GCM',
      iv: 'UGFzc3dvcmRJVkJ5dGVzMTI=',
      salt: 'UGFzc1NhbHRFeGFtcGxlMTY=',
      originalMimeType: 'application/json',
      originalName: 'passwords_backup.json',
      originalSize: 28000,
      checksum: 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9',
      encryptedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    encryptedContentPreview: '3f7c10b4923e847fa10940cc9824...',
    shared: false,
    starred: true,
    path: '/E2E_Secure_Vault',
    tags: ['Vault', 'Kredensial', 'AES-256'],
  },
  {
    id: 'f-5',
    accountId: 'acc-personal',
    accountEmail: 'alex.pratama.dev@gmail.com',
    accountName: 'Alex Pratama (Personal Vault)',
    name: 'Dokumen_Polis_Asuransi_Kesehatan.pdf',
    mimeType: 'application/pdf',
    category: 'pdf',
    size: 3420000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    isEncrypted: false,
    shared: true,
    shareSettings: {
      linkId: 'sh-link-102',
      shareUrl: 'https://xxcloud.internal/share/sh-link-102',
      accessRole: 'viewer',
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
      isPasswordProtected: false,
      allowDownload: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      accessCount: 3,
      status: 'active',
    },
    starred: false,
    path: '/Dokumen Pribadi',
    tags: ['Asuransi', 'Kesehatan'],
  },
  {
    id: 'f-6',
    accountId: 'acc-research',
    accountEmail: 'research.lab@university.ac.id',
    accountName: 'Lab Riset Multimedia (Academic)',
    name: 'Dataset_AI_Computer_Vision_Cleaned.zip',
    mimeType: 'application/zip',
    category: 'archive',
    size: 45200000000, // 45.2 GB
    modifiedTime: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    isEncrypted: false,
    shared: true,
    shareSettings: {
      linkId: 'sh-link-103',
      shareUrl: 'https://xxcloud.internal/share/sh-link-103',
      accessRole: 'editor',
      expiresAt: null, // No expiration
      isPasswordProtected: true,
      allowDownload: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
      accessCount: 42,
      status: 'active',
    },
    starred: true,
    path: '/Datasets/2026',
    tags: ['AI', 'Dataset', 'Heavy'],
  },
  {
    id: 'f-7',
    accountId: 'acc-research',
    accountEmail: 'research.lab@university.ac.id',
    accountName: 'Lab Riset Multimedia (Academic)',
    name: 'Draft_Jurnal_IEEE_Transactions_2026.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: 'document',
    size: 2890000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    isEncrypted: false,
    shared: false,
    starred: true,
    path: '/Publikasi',
    tags: ['IEEE', 'Paper', 'Draft'],
  },
  {
    id: 'f-8',
    accountId: 'acc-work',
    accountEmail: 'alex.corporate@company.com',
    accountName: 'Alex Pratama (Work Workspace)',
    name: 'Slide_Presentasi_Investor_Pitch_Deck.pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    category: 'presentation',
    size: 32000000,
    modifiedTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    isEncrypted: false,
    shared: true,
    shareSettings: {
      linkId: 'sh-link-104',
      shareUrl: 'https://xxcloud.internal/share/sh-link-104',
      accessRole: 'viewer',
      expiresAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // Expired!
      isPasswordProtected: false,
      allowDownload: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
      accessCount: 29,
      status: 'expired',
    },
    starred: true,
    path: '/Presentasi',
    tags: ['Pitch', 'Investor', 'Deck'],
  },
  {
    id: 'f-9',
    accountId: 'acc-personal',
    accountEmail: 'alex.pratama.dev@gmail.com',
    accountName: 'Alex Pratama (Personal Vault)',
    name: 'Koleksi_Foto_Dokumentasi_Keluarga_4K.zip',
    mimeType: 'application/zip',
    category: 'archive',
    size: 5120000000, // 5.12 GB
    modifiedTime: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    createdTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    isEncrypted: false,
    shared: false,
    starred: false,
    path: '/Media/Photos',
    tags: ['Foto', 'Keluarga'],
  },
];

export const INITIAL_SYNC_RULES: SyncRule[] = [
  {
    id: 'rule-1',
    name: 'Cermin Otomatis: Backup Dokumen Kerja ke Vault Pribadi',
    sourceAccountId: 'acc-work',
    targetAccountId: 'acc-personal',
    folderPath: '/Dokumen_Krusial',
    direction: 'one_way',
    autoSync: true,
    syncIntervalMinutes: 15,
    lastRun: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    status: 'idle',
    conflictResolution: 'keep_newer',
  },
  {
    id: 'rule-2',
    name: 'Sinkronisasi Dua Arah: Draft Riset & Paper',
    sourceAccountId: 'acc-work',
    targetAccountId: 'acc-research',
    folderPath: '/Kolaborasi_Riset',
    direction: 'two_way',
    autoSync: true,
    syncIntervalMinutes: 30,
    lastRun: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    status: 'idle',
    conflictResolution: 'keep_both',
  },
];

export const INITIAL_NOTIFICATIONS: DriveNotification[] = [
  {
    id: 'notif-1',
    type: 'file_change',
    title: 'Pembaruan Berkas Terdeteksi',
    message: 'File "Slide_Presentasi_Investor_Pitch_Deck.pptx" baru saja dimodifikasi di Google Drive Kerja.',
    accountEmail: 'alex.corporate@company.com',
    fileId: 'f-8',
    fileName: 'Slide_Presentasi_Investor_Pitch_Deck.pptx',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    read: false,
    severity: 'info',
  },
  {
    id: 'notif-2',
    type: 'security',
    title: 'Enkripsi End-to-End Berhasil',
    message: 'File "Kunci_Privat_Wallet_Keluarga.omnienc" diamankan dengan kunci enkripsi AES-256-GCM lokal.',
    accountEmail: 'alex.pratama.dev@gmail.com',
    fileId: 'f-3',
    fileName: 'Kunci_Privat_Wallet_Keluarga.omnienc',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    read: false,
    severity: 'success',
  },
  {
    id: 'notif-3',
    type: 'sync',
    title: 'Sinkronisasi Real-Time Selesai',
    message: 'Sinkronisasi cermin otomatis antara Google Drive Kerja dan Vault Pribadi selesai tanpa konflik.',
    accountEmail: 'alex.corporate@company.com',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    read: true,
    severity: 'success',
  },
  {
    id: 'notif-4',
    type: 'share',
    title: 'Tautan Berbagi Kedaluwarsa',
    message: 'Tautan berbagi untuk "Slide_Presentasi_Investor_Pitch_Deck.pptx" telah otomatis dinonaktifkan sesuai batas waktu.',
    accountEmail: 'alex.corporate@company.com',
    fileId: 'f-8',
    fileName: 'Slide_Presentasi_Investor_Pitch_Deck.pptx',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    read: true,
    severity: 'warning',
  },
];
